- name: Update Ubuntu servers
  hosts: ubuntu
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: 'yes'