---
- name: Manage local users and their SSH authorized keys on Linux servers
  hosts: test
  become: true
  vars:
    # List of users with SSH keys and their state
    users_and_keys:
      - user: "user1"
        state: "present"  # Set to "present" to create the user and add their keys
        keys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkGbau/ymNbG94suL4Oq7tdqldpqz... "
      - user: "user2"
        state: "present"   # Set to "absent" to remove the user and their keys
        keys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjVYHmegPGIVsm5ipU3K0qQFUsXV3+... "

  tasks:
    - name: Manage SSH authorized keys for present users
      ansible.posix.authorized_key:
        user: "{{ item.0.user }}"
        state: "present"
        key: "{{ item.1 }}"
      loop: "{{ query('subelements', users_and_keys, 'keys') }}"
      when: item.0.state == 'present'

    - name: Remove SSH authorized keys for absent users
      ansible.posix.authorized_key:
        user: "{{ item.0.user }}"
        state: "absent"
        key: "{{ item.1 }}"
      loop: "{{ query('subelements', users_and_keys, 'keys') }}"
      when: item.0.state == 'absent'